"use client";

import { motion } from "framer-motion";
import { Download, Share2, Target, BarChart3, Users, Zap } from "lucide-react";

export default function InvestorSnapshot() {
  return (
    <div className="max-w-5xl mx-auto p-6 lg:p-10">
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-8 gap-4">
        <div>
          <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
            Investor Snapshot
          </h1>
          <p className="text-slate-400 mt-2">
            A shareable, one-page summary of your fundability metrics.
          </p>
        </div>
        <div className="flex space-x-3">
          <button className="flex items-center px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors text-sm font-medium border border-slate-700 shadow-lg">
            <Share2 className="w-4 h-4 mr-2" /> Share Link
          </button>
          <button className="flex items-center px-4 py-2 bg-blaze-500 hover:bg-blaze-600 text-white rounded-lg transition-colors text-sm font-medium shadow-lg shadow-blaze-500/20">
            <Download className="w-4 h-4 mr-2" /> Export to PDF
          </button>
        </div>
      </div>

      {/* Snapshot Preview Container (Styled to look like a document) */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white text-slate-900 p-10 rounded-xl shadow-2xl relative overflow-hidden"
      >
        {/* Document Header */}
        <div className="flex justify-between items-start mb-12 border-b border-slate-200 pb-8">
          <div>
            <div className="text-3xl font-bold text-slate-900 mb-1">Acme Corp</div>
            <div className="text-slate-500 font-medium">B2B SaaS • Seed Stage • San Francisco, CA</div>
          </div>
          <div className="text-right">
            <div className="text-sm font-semibold text-slate-400 uppercase tracking-widest mb-1">Generated by</div>
            <div className="flex items-center justify-end font-bold text-blaze-500">
              <Zap className="w-4 h-4 mr-1" /> NextBlaze Validated
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mb-12">
          {/* Main Highlights */}
          <div className="col-span-2 space-y-8">
            <div>
               <h3 className="text-lg font-bold text-slate-900 mb-3 border-b-2 border-blaze-500 inline-block pb-1">The Opportunity</h3>
               <p className="text-slate-600 leading-relaxed">
                 Acme Corp is revolutionizing enterprise workflow automation with AI. We are solving a $10B problem in the unstructured data space, accelerating data entry times by 80% for Fortune 500 companies.
               </p>
            </div>

            <div className="grid grid-cols-2 gap-6">
              <div className="bg-slate-50 p-6 rounded-xl border border-slate-100">
                 <div className="flex items-center text-slate-500 mb-2">
                   <BarChart3 className="w-5 h-5 mr-2 text-blaze-500" /> MRR
                 </div>
                 <div className="text-3xl font-bold text-slate-900">$11,000</div>
                 <div className="text-sm text-green-600 font-medium mt-1">+10% MoM Growth</div>
              </div>
              <div className="bg-slate-50 p-6 rounded-xl border border-slate-100">
                 <div className="flex items-center text-slate-500 mb-2">
                   <Users className="w-5 h-5 mr-2 text-blaze-500" /> Active Customers
                 </div>
                 <div className="text-3xl font-bold text-slate-900">42</div>
                 <div className="text-sm text-slate-500 font-medium mt-1">Enterprise & Mid-Market</div>
              </div>
            </div>
          </div>

          {/* Sidebar Metrics */}
          <div className="col-span-1 bg-slate-50 rounded-xl p-6 border border-slate-100">
             <div className="mb-8">
               <div className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-2 flex items-center">
                 <Target className="w-4 h-4 mr-2" /> Fundability Score
               </div>
               <div className="text-5xl font-bold text-slate-900">68<span className="text-xl text-slate-400 font-normal">/100</span></div>
               <div className="w-full bg-slate-200 rounded-full h-2 mt-3">
                 <div className="bg-amber-500 h-2 rounded-full" style={{ width: '68%' }}></div>
               </div>
               <p className="text-xs text-slate-500 mt-2">Metrics verified via API connection.</p>
             </div>

             <div className="space-y-4">
               <div>
                  <div className="text-xs font-semibold text-slate-500 uppercase">Runway</div>
                  <div className="font-bold text-slate-900 text-lg">6.5 Months</div>
               </div>
               <div>
                  <div className="text-xs font-semibold text-slate-500 uppercase">Burn Rate</div>
                  <div className="font-bold text-slate-900 text-lg">$15k / Month</div>
               </div>
               <div>
                  <div className="text-xs font-semibold text-slate-500 uppercase">Funding Sought</div>
                  <div className="font-bold text-slate-900 text-lg">$1,500,000</div>
               </div>
             </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
